# helm upgrade --install ociregistry ../../charts/ociregistry\
#  --namespace ociregistry\
#  --create-namespace\
#  --values ./values-ingress.yml\
#  --dry-run=server
ingress:
  enabled: true
  hosts:
  - host: dtk.io
    paths:
    - path: /
      pathType: ImplementationSpecific

service:
  type: ClusterIP
  nodePort:
