apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ociregistry.fullname" . }}
  labels:
    {{- include "ociregistry.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ociregistry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ociregistry.labels" . | nindent 8 }}
	      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ociregistry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.args }}
        args:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ include "ociregistry.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.persistence.hostPath.enabled }}
      - name: images
        hostPath:
          type: {{ .Values.persistence.hostPath.type }}
          path: {{ .Values.persistence.hostPath.path }}
      {{- end }}
      {{- if .Values.persistence.emptyDir.enabled }}
      - name: images
        emptyDir:
          sizeLimit: {{ .Values.persistence.emptyDir.sizeLimit }}
      {{- end }}
      {{- if .Values.persistence.persistentVolumeClaim.enabled }}
      - name: images
        persistentVolumeClaim:
          {{- if .Values.persistence.persistentVolumeClaim.spec -}}
          claimName: {{ include "ociregistry.fullname" . }}
          {{- else }}
          claimName: {{ .Values.persistence.persistentVolumeClaim.claimName }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
