profile: cover.out

threshold:
  file: 65
  package: 70
  total: 75

override: []

exclude:
  paths:
    - api/
    - impl/ociregistry\.go

breakdown-file-name: ''

diff:
  base-breakdown-file-name: ''
