profile: cover.out

threshold:
  package: 55
  total: 60

override: []

exclude:
  paths:
    - api/
    - impl/ociregistry\.go
    - impl/metrics
    - mock/
    # something weird is happening between go test, go coverage, and go-test-coverage that is mis-reporting the coverage
    # at least for this file, and I don't have time to deal with it now (11-Nov-2025)
    - impl/config/config.go

breakdown-file-name: ''

diff:
  base-breakdown-file-name: ''
