profile: cover.out

threshold:
  package: 55
  total: 60

override: []

exclude:
  paths:
    - api/
    - impl/ociregistry\.go
    - impl/metrics

breakdown-file-name: ''

diff:
  base-breakdown-file-name: ''
