profile: cover.out

threshold:
  file: 65
  package: 70
  total: 80

override: []

exclude:
  paths:
    - ^impl/ociregistry\.go
    - ^api/

breakdown-file-name: ''

diff:
  base-breakdown-file-name: ''
