openapi: 3.0.3
info:
  title: OCI Registry - OpenAPI 3.0
  description: Pull-only pull-through caching registry
  termsOfService: ""
  contact:
    email:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description:
  url: ""
servers:
  - url: https://ociregistry/api/v2
tags: []
paths:
  /:
    connect:
      tags: []
      summary:
      description:
      operationId: connect
      parameters: []
      responses:
        '200':
          description:
          content: {}
  /v2/:
    get:
      tags: []
      summary:
      description:
      operationId: v2-default
      parameters: []
      responses:
        '200':
          description:
          content: {}
        '400':
          description:
        '401':
          description:
  /v2/auth:
    get:
      tags: []
      summary:
      description:
      operationId: v2-auth
      parameters:
      - name: authorization
        in: header
        description:
        required: true
        schema:
          type: string
      - name: scope
        in: query
        description:
        required: false
        schema:
          type: string
      - name: service
        in: query
        description:
        required: false
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '401':
          description:
  /v2/{org}/{image}/blobs/{digest}:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-org-image-blobs-digest
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    head:
      tags: []
      summary:
      description:
      operationId: v2-head-org-image-blobs-digest
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    delete:
      tags: []
      summary:
      description:
      operationId: v2-delete-org-image-blobs-digest
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '202':
          description:
          content: {}
        '404':
          description:
        '405':
          description:
  /v2/{image}/blobs/{digest}:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-image-blobs-digest
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    head:
      tags: []
      summary:
      description:
      operationId: v2-head-image-blobs-digest
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    delete:
      tags: []
      summary:
      description:
      operationId: v2-delete-image-blobs-digest
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '202':
          description:
          content: {}
        '404':
          description:
        '405':
          description:
  /v2/{name}/blobs/uploads:
    post:
      tags: []
      summary:
      description:
      operationId: v2-post-name-blobs-uploads
      parameters:
      - name: name
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: query
        description:
        required: false
        schema:
          type: string
      - name: mount
        in: query
        description:
        required: false
        schema:
          type: string
      - name: from
        in: query
        description:
        required: false
        schema:
          type: string
      responses:
        '201':
          description:
          content: {}
        '202':
          description:
          content: {}
        '400':
          description:
        '404':
          description:
  /v2/{name}/blobs/uploads/{reference}:
    put:
      tags: []
      summary:
      description:
      operationId: v2-put-name-blobs-uploads-reference
      parameters:
      - name: name
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: query
        description:
        required: false
        schema:
          type: string
      responses:
        '201':
          description:
          content: {}
        '400':
          description:
        '404':
          description:
    patch:
      tags: []
      summary:
      description:
      operationId: v2-patch-name-blobs-uploads-reference
      parameters:
      - name: name
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '202':
          description:
          content: {}
        '404':
          description:
        '416':
          description:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-name-blobs-uploads-reference
      parameters:
      - name: name
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '204':
          description:
          content: {}
        '404':
          description:
  /v2/{org}/{image}/manifests/{reference}:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-org-image-manifests-reference
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    head:
      tags: []
      summary:
      description:
      operationId: v2-head-org-image-manifests-reference
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    put:
      tags: []
      summary:
      description:
      operationId: v2-put-org-image-manifests-reference
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '201':
          description:
          content: {}
        '404':
          description:
    delete:
      tags: []
      summary:
      description:
      operationId: v2-delete-org-image-manifests-reference
      parameters:
      - name: org
        in: path
        description:
        required: true
        schema:
          type: string
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '202':
          description:
          content: {}
        '400':
          description:
        '404':
          description:
        '405':
          description:
  /v2/{image}/manifests/{reference}:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-image-manifests-reference
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    head:
      tags: []
      summary:
      description:
      operationId: v2-head-image-manifests-reference
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
    put:
      tags: []
      summary:
      description:
      operationId: v2-put-image-manifests-reference
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '201':
          description:
          content: {}
        '404':
          description:
    delete:
      tags: []
      summary:
      description:
      operationId: v2-delete-image-manifests-reference
      parameters:
      - name: image
        in: path
        description:
        required: true
        schema:
          type: string
      - name: reference
        in: path
        description:
        required: true
        schema:
          type: string
      responses:
        '202':
          description:
          content: {}
        '400':
          description:
        '404':
          description:
        '405':
          description:
  /v2/{name}/tags/list:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-name-tags-list
      parameters:
      - name: name
        in: path
        description:
        required: true
        schema:
          type: string
      - name: n
        in: query
        description:
        required: false
        schema:
          type: string
      - name: last
        in: query
        description:
        required: false
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '404':
          description:
  /v2/{name}/referrers/{digest}:
    get:
      tags: []
      summary:
      description:
      operationId: v2-get-name-referrers-digest
      parameters:
      - name: name
        in: path
        description:
        required: true
        schema:
          type: string
      - name: digest
        in: path
        description:
        required: true
        schema:
          type: string
      - name: artifactType
        in: query
        description:
        required: false
        schema:
          type: string
      responses:
        '200':
          description:
          content: {}
        '400':
          description:
        '404':
          description:
