- name: index.docker.io
  description: No auth, TLS if required by the server using OS trust store
  auth: {}
  tls: {}

- name: a-localhost:5000
  description: basic auth, TLS if required by the server using OS trust store
  auth:
    user: foobar
    password: frobozz
  tls: {}

- name: b-localhost:5000
  description: no auth, insecure TLS (no verify server) if TLS required by the server
  auth: {}
  tls:
    insecure_skip_verify: true

- name: c-localhost:5000
  description: no auth, insecure two-way TLS (no verify server) if TLS required by the server
  auth: {}
  tls:
    insecure_skip_verify: true
    cert: /path/to/cert
    key: /path/to/key

- name: d-localhost:5000
  description: no auth, secure two-way TLS, verify server using OS trust store
  auth: {}
  tls:
    cert: /path/to/cert
    key: /path/to/key

- name: e-localhost:5000
  description: no auth, secure two-way TLS, verify server using explicit CA
  auth: {}
  tls:
    cert: /path/to/cert
    key: /path/to/key
    ca:  /path/to/ca/that/trusts/server/cert