{
 "title": "Ociregistry metrics",
 "description": "This dashboard measures the performance and throughput characteristics of the Ociregistry distribution server.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total manifest pulls",
   "type": "timeseries",
   "description": "Rate of manifest pulls",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ociregistry_manifest_pulls_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total blob pulls",
   "type": "timeseries",
   "description": "Most images consist of multiple blobs, this shows the running rate of blob pulls which should exceed manifest pulls",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ociregistry_blob_pulls_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached pulls by namespace",
   "type": "timeseries",
   "description": "Rate of pulls from cache, bucketed by upstream namespace (e.g. docker.io, ghcr,io, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ociregistry_cached_pulls_by_ns_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstreams  pulls by namespace",
   "type": "timeseries",
   "description": "Rate of pulls from upstreams, bucketed by namespace (e.g. docker.io, quay.io)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(ociregistry_upstream_pulls_by_ns[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File system blob bytes",
   "type": "stat",
   "description": "Blob bytes on the file system",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ociregistry_blob_bytes_on_disk_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File system manifest bytes",
   "type": "stat",
   "description": "Manifest bytes on the file system",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ociregistry_manifest_bytes_on_disk_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached manifests",
   "type": "stat",
   "description": "Count of manifests cached in memory. This will exceed the manifest count on the filesystem because manifests are added to the in-mem cache by tag and by digest, for example",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ociregistry_cached_manifest_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached blobs",
   "type": "stat",
   "description": "Count of cached blobs",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ociregistry_cached_blob_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "V2 API endpoint hits",
   "type": "timeseries",
   "description": "Total hits against the OCI distribution spec v2 endpoints that are implemented by the server (not all endpoints are implemented)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(ociregistry_v2_api_endpoint_hits_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "timeseries",
   "description": "Valid errors should only result from concurrent pruning. Inspect the logs if errors seem unrelated to that",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(ociregistry_api_errors_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}