#!/usr/bin/env bash
#
# Run this from project root. Usage:
#
# hack/test-local-server <path to image list>
#
# E.g.:
#
# hack/test-local-server hack/image-list
#

if [[ "$#" -ne 1 ]]; then
  echo "need image list file in arg 1"
  exit 1
fi

image_cache_dir=$(mktemp -d)

./bin/server --image-path=$image_cache_dir --port=8888 --preload-images=$1 --log-level=debug

echo "image cache is $image_cache_dir"
echo "to shut the server down: curl localhost:8888/cmd/stop"
