#!/usr/bin/env bash

container=$(docker run -d\
            --name ociregistry\
            -p 8080:8080\
            --user $(id -u):$(id -g)\
            -v $PWD/images:/var/lib/ociregistry\
            ociregistry:1.0.0 --log-level=debug)

docker logs $container -f
