# helm upgrade --install ociregistry ociregistry\
#  --namespace ociregistry\
#  --create-namespace\
#  --values ./test-values.yml\
#  --dry-run=server
ingress:
  enabled: true
  hosts:
  - host: dtk.io
    paths:
    - path: /
      pathType: ImplementationSpecific

serverConfig:
  config:

service:
  type: ClusterIP
  nodePort:
