{
 "title": "Ociregistry / Go Runtime",
 "description": "This dashboard measures go runtime metrics",
 "tags": [ "ociregistry" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "memory_classes_total_usage_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_total_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_heap_released_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_heap_objects_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_heap_stacks_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_heap_unused_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_metadata_mcache_free_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_metadata_mcache_inuse_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_metadata_mspan_free_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_metadata_mspan_inuse_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_metadata_other_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_os_stacks_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_other_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_profiling_buckets_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_classes_heap_free_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_threads{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"ociregistry-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(gc_cycles_total_gc_cycles{job=\"ociregistry-metrics\"}[$__rate_interval])",
     "legendFormat": "Completed GC cycles"
    }
   ]
  },
  {
   "title": "Mutex Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(sync_mutex_wait_total_seconds{job=\"ociregistry-metrics\"}[$__rate_interval])",
     "legendFormat": "Sync mutext wait seconds"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"ociregistry-metrics\"}[$__rate_interval])",
     "legendFormat": "Process Network Rcv Bytes"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total{job=\"ociregistry-metrics\"}[$__rate_interval])",
     "legendFormat": "Process Network Tx bytes"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"ociregistry-metrics\"}",
     "legendFormat": "Resident Mem"
    }
   ]
  }
 ]
}