{{- if .Values.persistence.hostPath.enabled }}
  {{- if .Values.persistence.persistentVolumeClaim.enabled }}
    {{- fail "Error: 'persistence.hostPath' and 'persistence.persistentVolumeClaim' are mutually exclusive" }}
  {{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ociregistry.fullname" . }}
  labels:
    {{- include "ociregistry.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ociregistry.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registry-config-cm.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ociregistry.labels" . | nindent 8 }}
	      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ociregistry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      {{- with .Values.sidecarContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - name: {{ .Chart.Name }}
        command:
        - /ociregistry/server
        args:
        {{- if .Values.serverConfig.configuration }}
        - --config-file
        - {{ .Values.serverConfig.mountPath | default "/var/ociregistry/config" }}/registry-config.yaml
        {{- end }}
        - serve
        {{- if .Values.health.port }}
        - --health
        - {{ .Values.health.port | quote }}
        {{- end }}
        {{- if and .Values.serverConfig.configuration .Values.serverConfig.configuration.health }}
        - --health
        - {{ .Values.serverConfig.configuration.health | quote }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "ociregistry.image" (dict "img" .Values.image.ociregistry) }}
        imagePullPolicy: {{ .Values.image.ociregistry.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        {{- if or .Values.health.port (and .Values.serverConfig.configuration .Values.serverConfig.configuration.health) }}
        - name: health
          {{- if .Values.health.port }}
          containerPort: {{ .Values.health.port }}
          {{- end }}
          {{- if and .Values.serverConfig.configuration .Values.serverConfig.configuration.health }}
          containerPort: {{ .Values.serverConfig.configuration.health }}
          {{- end }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: health
        readinessProbe:
          httpGet:
            path: /health
            port: health
        {{- end }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.serverConfig.configuration }}
        - name: config
          mountPath: {{ .Values.serverConfig.mountPath | default "/var/ociregistry/config" }}
          readOnly: true
        {{- end }}
        {{- if or .Values.serverTls.enabled .Values.serverTls.secretName }}
        - name: server-tls
          mountPath: /etc/pki/ociregistry
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.volumes }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- if and .Values.serverTls.enabled (not .Values.serverTls.secretName) }}
      - name: server-tls
        secret:
          secretName: {{ include "ociregistry.fullname" . }}-tls
      {{- end }}
      {{- if and .Values.serverTls.enabled .Values.serverTls.secretName }}
      - name: server-tls
        secret:
          secretName: {{ .Values.serverTls.secretName }}
      {{- end }}
      {{- if .Values.persistence.hostPath.enabled }}
      - name: images
        hostPath:
          type: {{ .Values.persistence.hostPath.type }}
          path: {{ .Values.persistence.hostPath.path }}
      {{- end }}
      {{- if and .Values.persistence.emptyDir.enabled (not .Values.persistence.hostPath.enabled) (not .Values.persistence.persistentVolumeClaim.enabled) }}
      - name: images
        emptyDir:
          sizeLimit: {{ .Values.persistence.emptyDir.sizeLimit }}
      {{- end }}
      {{- if .Values.persistence.persistentVolumeClaim.enabled }}
      - name: images
        persistentVolumeClaim:
          {{- if .Values.persistence.persistentVolumeClaim.existingClaimName }}
          claimName: {{ .Values.persistence.persistentVolumeClaim.existingClaimName }}
          {{- else }}
          claimName: {{ include "ociregistry.fullname" . }}
          {{- end }}
      {{- end }}
      {{- if .Values.serverConfig.configuration }}
      - name: config
        configMap:
          name: {{ include "ociregistry.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
