{{- if .Values.serverTls.enabled -}}
{{- if not .Values.serverTls.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ociregistry.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.serverTls.cert  | b64enc }}
  tls.key: {{ .Values.serverTls.key  | b64enc }}
  ca.crt: {{ .Values.serverTls.ca  | b64enc }}
{{- end }}
{{- end }}
