// Package apiimpl has the implementation of the api generated by the
// oapi-codegen tool from the open API spec. The oapi-codegen tool generates
// all the scaffolding into the "api" dir.
package apiimpl
