// Package apiimpl has the implementation of the api generated by the
// oapi-codegen tool from the open API spec. The oapi-codegen tool generates
// all the scaffolding into the "api" dir. This package has implementations
// for the API methods required to support a pull-only registry.
package apiimpl
