// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

// CmdBloblistParams defines parameters for CmdBloblist.
type CmdBloblistParams struct {
	Substr *string `form:"substr,omitempty" json:"substr,omitempty"`
}

// CmdImagelistParams defines parameters for CmdImagelist.
type CmdImagelistParams struct {
	Pattern *string `form:"pattern,omitempty" json:"pattern,omitempty"`
	Digest  *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// CmdManifestlistParams defines parameters for CmdManifestlist.
type CmdManifestlistParams struct {
	Pattern *string `form:"pattern,omitempty" json:"pattern,omitempty"`
}

// V2AuthParams defines parameters for V2Auth.
type V2AuthParams struct {
	Scope         *string `form:"scope,omitempty" json:"scope,omitempty"`
	Service       *string `form:"service,omitempty" json:"service,omitempty"`
	Authorization string  `json:"authorization"`
}

// V2GetImageManifestsReferenceParams defines parameters for V2GetImageManifestsReference.
type V2GetImageManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2HeadImageManifestsReferenceParams defines parameters for V2HeadImageManifestsReference.
type V2HeadImageManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2PostNameBlobsUploadsParams defines parameters for V2PostNameBlobsUploads.
type V2PostNameBlobsUploadsParams struct {
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
	Mount  *string `form:"mount,omitempty" json:"mount,omitempty"`
	From   *string `form:"from,omitempty" json:"from,omitempty"`
}

// V2PutNameBlobsUploadsReferenceParams defines parameters for V2PutNameBlobsUploadsReference.
type V2PutNameBlobsUploadsReferenceParams struct {
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// V2GetNameReferrersDigestParams defines parameters for V2GetNameReferrersDigest.
type V2GetNameReferrersDigestParams struct {
	ArtifactType *string `form:"artifactType,omitempty" json:"artifactType,omitempty"`
}

// V2GetNameTagsListParams defines parameters for V2GetNameTagsList.
type V2GetNameTagsListParams struct {
	N    *string `form:"n,omitempty" json:"n,omitempty"`
	Last *string `form:"last,omitempty" json:"last,omitempty"`
}

// V2GetOrgImageManifestsReferenceParams defines parameters for V2GetOrgImageManifestsReference.
type V2GetOrgImageManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2HeadOrgImageManifestsReferenceParams defines parameters for V2HeadOrgImageManifestsReference.
type V2HeadOrgImageManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}
