// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package models

// V2AuthParams defines parameters for V2Auth.
type V2AuthParams struct {
	Scope         *string `form:"scope,omitempty" json:"scope,omitempty"`
	Service       *string `form:"service,omitempty" json:"service,omitempty"`
	Authorization string  `json:"authorization"`
}

// V2PostNameBlobsUploadsParams defines parameters for V2PostNameBlobsUploads.
type V2PostNameBlobsUploadsParams struct {
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
	Mount  *string `form:"mount,omitempty" json:"mount,omitempty"`
	From   *string `form:"from,omitempty" json:"from,omitempty"`
}

// V2PutNameBlobsUploadsReferenceParams defines parameters for V2PutNameBlobsUploadsReference.
type V2PutNameBlobsUploadsReferenceParams struct {
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// V2GetNameReferrersDigestParams defines parameters for V2GetNameReferrersDigest.
type V2GetNameReferrersDigestParams struct {
	ArtifactType *string `form:"artifactType,omitempty" json:"artifactType,omitempty"`
}

// V2GetNameTagsListParams defines parameters for V2GetNameTagsList.
type V2GetNameTagsListParams struct {
	N    *string `form:"n,omitempty" json:"n,omitempty"`
	Last *string `form:"last,omitempty" json:"last,omitempty"`
}
