// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

// CmdBloblistParams defines parameters for CmdBloblist.
type CmdBloblistParams struct {
	Substr *string `form:"substr,omitempty" json:"substr,omitempty"`
	Count  *int    `form:"count,omitempty" json:"count,omitempty"`
}

// CmdImagelistParams defines parameters for CmdImagelist.
type CmdImagelistParams struct {
	Pattern *string `form:"pattern,omitempty" json:"pattern,omitempty"`
	Digest  *string `form:"digest,omitempty" json:"digest,omitempty"`
	Count   *int    `form:"count,omitempty" json:"count,omitempty"`
}

// CmdManifestlistParams defines parameters for CmdManifestlist.
type CmdManifestlistParams struct {
	Pattern *string `form:"pattern,omitempty" json:"pattern,omitempty"`
	Count   *int    `form:"count,omitempty" json:"count,omitempty"`
}

// CmdPruneParams defines parameters for CmdPrune.
type CmdPruneParams struct {
	Type   string  `form:"type" json:"type"`
	Dur    *string `form:"dur,omitempty" json:"dur,omitempty"`
	Expr   *string `form:"expr,omitempty" json:"expr,omitempty"`
	DryRun *string `form:"dryRun,omitempty" json:"dryRun,omitempty"`
	Count  *int    `form:"count,omitempty" json:"count,omitempty"`
}

// V2AuthParams defines parameters for V2Auth.
type V2AuthParams struct {
	Scope         *string `form:"scope,omitempty" json:"scope,omitempty"`
	Service       *string `form:"service,omitempty" json:"service,omitempty"`
	Authorization string  `json:"authorization"`
}

// V2PostNameBlobsUploadsParams defines parameters for V2PostNameBlobsUploads.
type V2PostNameBlobsUploadsParams struct {
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
	Mount  *string `form:"mount,omitempty" json:"mount,omitempty"`
	From   *string `form:"from,omitempty" json:"from,omitempty"`
}

// V2PutNameBlobsUploadsReferenceParams defines parameters for V2PutNameBlobsUploadsReference.
type V2PutNameBlobsUploadsReferenceParams struct {
	Digest *string `form:"digest,omitempty" json:"digest,omitempty"`
}

// V2GetNameReferrersDigestParams defines parameters for V2GetNameReferrersDigest.
type V2GetNameReferrersDigestParams struct {
	ArtifactType *string `form:"artifactType,omitempty" json:"artifactType,omitempty"`
}

// V2GetNameTagsListParams defines parameters for V2GetNameTagsList.
type V2GetNameTagsListParams struct {
	N    *string `form:"n,omitempty" json:"n,omitempty"`
	Last *string `form:"last,omitempty" json:"last,omitempty"`
}

// V2GetS1ManifestsReferenceParams defines parameters for V2GetS1ManifestsReference.
type V2GetS1ManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2HeadS1ManifestsReferenceParams defines parameters for V2HeadS1ManifestsReference.
type V2HeadS1ManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2GetS1S2ManifestsReferenceParams defines parameters for V2GetS1S2ManifestsReference.
type V2GetS1S2ManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2HeadS1S2ManifestsReferenceParams defines parameters for V2HeadS1S2ManifestsReference.
type V2HeadS1S2ManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2GetS1S2S3ManifestsReferenceParams defines parameters for V2GetS1S2S3ManifestsReference.
type V2GetS1S2S3ManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}

// V2HeadS1S2S3ManifestsReferenceParams defines parameters for V2HeadS1S2S3ManifestsReference.
type V2HeadS1S2S3ManifestsReferenceParams struct {
	Ns *string `form:"ns,omitempty" json:"ns,omitempty"`
}
