#!/usr/bin/env bash
#
# This is a helper script to make docker images that can be loaded into a local
# docker registry and then the ociregistry can pull from. The script helps load the
# ociregistry with a large number of images to perform some volume testing without
# having to pull from actual registries like quay or dockerhub. These images can't be
# used for anything but the script can generate large numbers of them.
#

set -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "$#" -ne 1 ]]; then
  echo "need image count in arg 1"
  exit 1
fi

config='{"architecture":"amd64","config":{"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/hello"],"WorkingDir":"/"},"created":"2025-08-08T19:05:17Z","history":[{"created":"2025-08-08T19:05:17Z","created_by":"COPY hello / # buildkit","comment":"buildkit.dockerfile.v0"},{"created":"2025-08-08T19:05:17Z","created_by":"CMD [\"/hello\"]","comment":"buildkit.dockerfile.v0","empty_layer":true}],"os":"linux","rootfs":{"type":"layers","diff_ids":[LAYERDIFFIDS]}}'

manifest='
[
   {
      "config": "sha256:CONFIGSHA",
      "repoTags": [
         "docker.io/IMAGENAME:vTAG"
      ],
      "layers": [
         LAYERS
      ]
   }
]'

image_count=$1
layer_count=5

cur=1
while [[ $cur -le $image_count ]]; do
  rm -f $script_dir/image/*

  # create image name and tag
  r1=$(head /dev/urandom | tr -dc a-z0-9 | head -c 10)
  r2=$(head /dev/urandom | tr -dc a-z0-9 | head -c 10)
  imagename="$r1-$r2"
  imagetag="${RANDOM:1:3}.${RANDOM:1:3}"

  # create layers
  layer=1
  while [[ $layer -le $layer_count ]]; do
    layer_content=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20)
    echo $layer_content >| $script_dir/layer_content
    tar -cf $script_dir/image/TEMP.tar layer_content
    layersha=$(sha256sum $script_dir/image/TEMP.tar | awk '{print $1}')
    mv $script_dir/image/TEMP.tar $script_dir/image/$layersha.tar
    ((layer++))
  done

  # create layer and diff id content to interpolate into manifest.json and
  # the config layer
  diff_ids=""
  layers=""
  diffsep=""
  layersep=""

  while IFS= read layer; do
    layer=$(echo $layer | cut -d / -f 2)
    diff_ids="${diff_ids}${diffsep}\"sha256:${layer%.*}\""
    layers="${layers}${layersep}\"$layer\""
    diffsep=", "
    layersep=",\n         "
  done < <(ls image/*.tar)

  # generate the config layer
  echo "$config" | sed -e "s/LAYERDIFFIDS/$diff_ids/" > $script_dir/image/TEMP
  configsha=$(sha256sum $script_dir/image/TEMP | awk '{print $1}')
  mv $script_dir/image/TEMP $script_dir/image/sha256:$configsha

  # generate manifest.json
  echo "$manifest" | sed\
    -e "s/LAYERS/$layers/"\
    -e "s/CONFIGSHA/$configsha/"\
    -e "s/IMAGENAME/$imagename/"\
    -e "s/TAG/$imagetag/"\
    > $script_dir/image/manifest.json

  # create the tar - it can be loaded into docker, e.g. docker load -i image.n.tar
  pushd $script_dir/image
  tar -cf ../image.$cur.tar *
  popd
  ((cur++))
done
