#!/usr/bin/env bash
#
# Repeatedly prunes and re-pulls until stopped. Accepts an optional arg which is
# a filter. This supports running multiple instances of this script concurrently. E.g.:
# in console 1:
#
#   ./prune-and-pull -0001:
#
# Then in console 2
#
#   ./prune-and-pull -0002:
#
# and so on.
#
# Ociregistry must be configured with config.yaml to pull from the ubuntu.me registry
# on plain http.
#

set -e

filter=*
if [[ -n "$1" ]]; then
  filter=$1
fi

rand=$RANDOM
while true; do
  docker images | grep ubuntu.me | awk '{print $1 ":" $2}' | while read image; do
    # e.g. ubuntu.me:5000/7l4kfql7b6-dy9dt9m9ej-0004:v986.174
    if [[ $image == *$filter* ]]; then
      # ignore if not cached for some reason
      curl -X DELETE "localhost:8888/cmd/prune?type=pattern&expr=$image&dryRun=false" || true
    fi
  done

  docker images | grep ubuntu.me | awk '{print $1 ":" $2}' | while read image; do
    if [[ $image == *$filter* ]]; then
      imgpull "localhost:8888/$image" ~/tmp/deleteme.$rand.tar --scheme http
    fi
  done
done
