#!/usr/bin/env bash
#
# Pulls through ociregistry from Docker registry. Accepts an optional arg which is
# a filter. This supports running multiple instances of this script concurrently. E.g.:
# in console 1:
#
#   ./pullthru -0001:
#
# Then in console 2
#
#   ./pullthru -0002:
#
# and so on.
#
# Ociregistry must be configured with config.yaml to pull from the ubuntu.me registry
# on plain http.
#

set -e

filter=*
if [[ -n "$1" ]]; then
  filter=$1
fi

imgcnt=0
while read image; do
  # e.g. ubuntu.me:5000/33tpy3hx9u-8wo7i2rp97-0005:v172.884
  if [[ $image == *$filter* ]]; then
    imgpull "localhost:8888/$image" ~/tmp/imgpull.tar --scheme http
    ((++imgcnt))
  fi
done < <(docker images | grep ubuntu.me | awk '{print $1 ":" $2}')

echo "pulled $imgcnt images"
