name: Chart

on:
  push:
    tags:        
      - '**'

jobs:
  publish_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Helm Docs
        shell: bash
        run: |
          curl -LO https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz
          tar -xf helm-docs_1.14.2_Linux_x86_64.tar.gz helm-docs
          sudo mv helm-docs /usr/local/bin

      - name: Build the Helm chart
        shell: bash
        run: |
          make helm-docs helm-package

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_CI_ACCOUNT }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Push the Helm chart
        shell: bash
        run: |
          make helm-push
